backbone:
  config: mit_b1
  stride: [4, 2, 2, 1]
  comments: None

dataset:
  root_dir: ./data/PourIt/seen
  name_list_dir: ./data/PourIt/seen
  num_classes: 2
  crop_size: 512
  rescale_range: [1.0, 1.1]
  ignore_index: 255

work_dir:
  dir: logs/pourit_ours
  ckpt_dir: checkpoints
  pred_dir: predictions
  tb_logger_dir: tb_logger

train:
  split: train
  samples_per_gpu: 2
  max_iters: 20000
  cam_iters: 2000
  eval_iters: 2000
  log_iters: 200

cam:
  scales: [1, 0.5, 1.5]

val:
  split: val

optimizer:
  type: AdamW
  learning_rate: 6e-5
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  warmup_iter: 1500
  warmup_ratio: 1e-6
  power: 1.0
